spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/my_test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456



#spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/onwn_test
        #url: jdbc:postgresql://10.149.7.70:18921/oss_zynl2db?currentSchema=res_res_sch&useSSL=false&useUnicode=true&characterEncoding=UTF-8
        username: postgres
        password: 752404
        driverClassName: org.postgresql.Driver
server:
  port: 12105
  servlet:
    context-path: /automation-quartz-one
management:
  health:
    db:
      enabled: false



